config/routes.rb
Hotels::Application.routes.draw do

  resources :locations

  resources :hotels_roomtypes

  get "accounts/profile"

  resources :hotel_types
  resources :room_types    
  resources :user_types
  resources :hotels_facilities
  resources :messages

  resources :hotels do
    resources :reviews
    resources :hotels_roomtypes
    resources :photos    
  end
#  resources :room_types
  resources :facilities
  devise_for :users, :path_names => {:sign_up => "register"}
  

  get "home/index"
  match "hotels/search/:location_name" => "hotels#browse_by_location", :as =>  "search_by_location"
  match "hotels/search" => "hotels#search", :as =>  "search_by"
  
  match "/contact-us" => "messages#new", :as=> "contact_us"
  match "/travel-guides" => "home#guides", :as=> "guides"
  match "/thankyou" => "messages#thankyou"
  match "/admin" =>"sessions#new"

  match "browse/:type_name/:location_name" => "hotels#find_by_location_of_hotel_type", :as => "find_by_location_of_hotel_type"  
  match "browse/:type_name" => "hotels#browse", :as => "browse_by"
  match "browse_by/:location_name/:type_name" => "hotels#browse_by_hotel_type_in_location", :as => "browse_by_hotel_type_in_location"     
  match "browse_by/:location_name" => "hotels#browse_by_location", :as => "browse_by_location"     
  
  match "hotels/:hotel_name/details" => "hotels#show" , :as => "details"  
  match "user-profile" => "accounts#profile", :as => :user_profile
  match "/about" => "home#about"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  

#  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location" 

  match "/deals/:location_name/:type_name" => "hotels#find_by_hotel_type_in_location", :as => "find_by_hotel_type_in_location"     
  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location"   
    match "/deals" => "hotels#deals", :as =>"deals"
  root :to => "home#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @menu_state = "class=active"
    @hotel_types = HotelType.all
    @top_hotels = Hotel.top_hotels

  end
  

  def guides
    @menu_state_g = "class=active"
  end

  def under_construction
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="terms">
	<div class="heading">			
		<h2>About Us</h2>
	</div>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
</div>

app/views/home/guides.html.erb
<div class="guides">
	<div class="summary">
		<div class="win-box-top"></div>
		<div class="win-box">
			<div class="heading">
				<h2>Emergencies</h2>
			</div>
			<p>
				For police, medical or fire emergencies dial 999 or 112 free from any phone.
			</p>
			<div class="heading">
				<h2>Currency</h2>
			</div>
			<p>
				Britain's currency is pound sterling (£). There are one hundred pence to one pound. You will encounter coins worth 1p, 2p, 5p, 10p, 20p, 50p, £1, and £2. Notes come in £5, £10, £20 and £50. You can withdraw money from cash machines all over the city, although be wary that some machines in shops may charge you for withdrawing your money (usually £1.50 - £1.75).
			</p>
			<div class="heading">
				<h2>Visa &amp; Immigration</h2>
			</div>
			<p>
				EU residents do not need a visa to enter the country and visitors from USA, Canada, Australia and New Zealand can also enter without a visa for up to 6 months provided that you can prove how you will support yourself during your stay.
			</p>
			<div class="heading">
				<h2>Public Holidays</h2>
			</div>	
			<p>
				Good Friday: 2nd April<br />
				Easter Monday: 5th April<br />
				May Bank Holiday: 3rd May<br />
				Spring Bank Holiday: 31st May<br />
				Summer Bank Holiday: 30th August<br />
				Christmas: 25th December<br />
				Boxing Day: 26th December<br />
			</p>
		</div>
		<div class="win-box-bottom"></div>
	</div>
	<div class="left-area">
		<div class="information">
			<div class="heading">
				<h2>City Guides</h2>
			</div>
			<p>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor.
			</p>
			<p>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor.
			</p>
			<div class="heading">
				<h2>Transports</h2>
			</div>
			<p>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor.
			</p>
			<p>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor.
			</p>
			<p>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor.
			</p>
			<div class="heading">
				<h2>Useful Links</h2>
			</div>
			<a href="http://tlf.gov.uk">Transport for London</a><br />
			<a href="http://www.britishmuseum.org/">British Museum</a>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% title "Cyper Hotels, Find hotels in London, Deals" %>
<% javascript 'jquery-ui-1.8.9.custom.min','jquery.cycle.all.min','application'%>

      <div class="banner">
      	<div class="images"  id="pics" style="position:relative;">
				<div class="cycle">
					<a href="/hotels/2" title="Homely House">
						<img src="media/HomelyHouse/01.jpg" alt="homely house" />
					</a>
				</div>
					<div class="cycle">
						<a href="/hotels/1" title="Homely House">
							<img src="media/hotel_01.jpg" alt="hotels" />
						</a>
					</div>
					<div class="cycle">
						<a href="/hotels/4" title="Majestic Inns">
							<img src="media/MajesticInns/01.jpg" alt="MajesticInns" />
						</a>
					</div>
					<div class="cycle">	
						<a href="/browse/Apartment Hotels" title="Sea View Inn">
							<img src="media/seaviewinn/01.jpg" alt="Sea View Inn" />
						</a>
					</div>
				</div>      
      <div class="search-box">
        <div class="heading">
      	  <h2 class="search-for-hotels" title="Search for Hotels">Search for Hotels</h2>
      	</div>
          <% form_tag search_by_path(params[:search]) do %>    			
      		<ul>
      			<li>
      				<label>Location</label>
		    			<%= text_field_tag :search, params[:search], :id=> 'search-field', :class=>'txtfield', :placeholder => 'Search Location' %>

      			</li>
      			<li>
      				<label>Arrival Date</label>
      				<input id="datepicker" name="arrival-date" type="text" class="arrival-date txtfield" />
      			</li>
      			<li>
      				<label>How many person?</label>
      				<select>
      				  <option value="1">1 Person</option>
      				  <option value="2">2 People</option>
      				  <option value="3">3 People</option>
      				  <option value="4">4 People</option>
      				</select>							
      			</li>
      			<li>
      				<label>Number of Nights?</label>
      				<select>
      				  <option value="1">1</option>
      				  <option value="2">2</option>
      				  <option value="3">3</option>
      				  <option value="4">4</option>
      				</select>							
      			</li>
      			<li class="send-enquiry">
      			  <%= submit_tag '', :name => :nil, :class => 'submit-button' %>
      			</li>
      		</ul>
    		<% end %>			
      </div>
      </div>
		<div class="home-left">
			<div class="browse-by">
				<div class="hotel-types">
					<div class="heading">
						<h2 title="Browse by Hotel Types">Browse by Hotel Types</h2>
					</div>
					<ul>
					  <% @hotel_types.each do |hotel_type|%>  				
						  <li><%= link_to hotel_type.name , browse_by_path(hotel_type.name) %></li>
					  <% end %>
					</ul>
				</div>
				<div class="hotel-types">
					<div class="heading">
						<h2 title="Browse by Popular Location">Browse by Popular Location</h2>
					</div>
					<ul>
						<li>
							<%= link_to "West End", browse_by_location_path("west end")%>							
						</li>
						<li>
							<%= link_to "Ealing", browse_by_location_path("Ealing")%>
						</li>
						<li>
							<%= link_to "Kilburn", browse_by_location_path("Kilburn")%>
						</li>
						<li>
							<%= link_to "Greenford", browse_by_location_path("greenford")%>
						</li>
						<li>
							<%= link_to "Covent Garden", browse_by_location_path("covent garden")%>
						</li>
						<li>
							<%= link_to "Hounslow", browse_by_location_path("hounslow")%>
						</li>
						<li>
							<%= link_to "Paddington", browse_by_location_path("paddington")%>
						</li>
						<li>
							<%= link_to "Hydepark", browse_by_location_path("hyde park")%>
						</li>
						<li>
							<%= link_to "Kensington", browse_by_location_path("kensington")%>
						</li>
					</ul>				
				</div>
			</div>
			<div class="full-width">
				<div class="one-third">
					<div class="small-box">
						<div class="heading">
							<h2 class="customer-service">
								Attractions in Town
							</h2>
						</div>	
							<ul>
								<li><a href="http://www.madametussauds.com/" title="Madame Taussauds">Madame Taussauds</a></li>
								<li><a href="http://www.londoneye.com/ " title="London Eye">London Eye</a></li>
								<li><a href="http://www.britishmuseum.org" title="British Museum">British Museum</a></li>
								<li><a href="http://www.hrp.org.uk/toweroflondon/" title="Tower of London">Tower of London</a></li>
								<li><a href="http://www.nationalgallery.org.uk/" title="National Gallery">National Gallery</a></li>				
								<li><a href="http://www.sciencemuseum.org.uk/" title="Science Museum">Science Museum</a></li>

							</ul>
					</div>
				</div>
				<div class="one-third">
					<div class="small-box">
						<div class="heading">
							<h2 class="Shopping">Shopping</h2>
						</div>
						<ul>
							<li><a href="http://uk.westfield.com/london/" title="Westfield">Westfield London</a></li>
							<li><a href="http://www.harrods.com/" title="Harrods">Harrods</a></li>
							<li><a href="http://www.houseoffraser.co.uk" title="House of Fraser">House of Fraser</a></li>
							<li><a href="http://www.coventgardenlondonuk.com" title="">Convent Garden</a></li>
							<li><a href="http://www.marksandspencer.com" title="">Marks and Spencer</a></li>																																
							<li><a href="http://selfridges.com" title="Selfridges">Selfridges</a></li>								
						</ul>
					</div>
				</div>
			</div>					
			
		</div>	
  			<div class="top-hotels">
  				<div class="heading">			
  					<h2>Top Hotels in Town</h2>
  				</div>	
        	<div class="list">
        	  <% @top_hotels.each do |hotel| %>
        		<div class="hotel-box">
        				<div class="thumb">
            			<% unless hotel.photos.first.nil? %>
            				<%= link_to image_tag(hotel.photos.first.uploaded_file.url(:thumb), :alt => ""), details_path(hotel.name) %>
            			<% end %>
        				</div>
        				<div class="details">
        					<h3><%= link_to hotel.name , details_path(hotel.name) %></h3>
        					<div class="loc"><%= hotel.location.name %></div>
        					<div class="s<%= hotel.star %>"></div>
        					<div class="reviews"><%= link_to "Reviews (#{hotel.reviews.count})", hotel_reviews_path(hotel) %></div>
        				</div>
        		</div>
        		<% end %>
        	</div>
  			</div>
  	
      </div>

app/views/home/privacy.html.erb
<div class="terms">
	<div class="heading">			
		<h2>Privacy</h2>
	</div>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
</div>

app/views/home/terms.html.erb
<div class="terms">
	<div class="heading">			
		<h2>Terms</h2>
	</div>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
	<p>
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt 
		ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ulla
		mcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iri
		ure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla faci
		lisis at vero eros et accumsan et iusto odio.
	</p>
</div>