config/routes.rb
Hotels::Application.routes.draw do

  resources :locations

  resources :hotels_roomtypes

  get "accounts/profile"

  resources :hotel_types
  resources :room_types    
  resources :user_types
  resources :hotels_facilities
  resources :messages

  resources :hotels do
    resources :reviews
    resources :hotels_roomtypes
    resources :photos    
  end
#  resources :room_types
  resources :facilities
  devise_for :users, :path_names => {:sign_up => "register"}
  

  get "home/index"
  match "hotels/search/:location_name" => "hotels#browse_by_location", :as =>  "search_by_location"
  match "hotels/search" => "hotels#search", :as =>  "search_by"
  
  match "/contact-us" => "messages#new", :as=> "contact_us"
  match "/travel-guides" => "home#guides", :as=> "guides"
  match "/thankyou" => "messages#thankyou"
  match "/admin" =>"sessions#new"

  match "browse/:type_name/:location_name" => "hotels#find_by_location_of_hotel_type", :as => "find_by_location_of_hotel_type"  
  match "browse/:type_name" => "hotels#browse", :as => "browse_by"
  match "browse_by/:location_name/:type_name" => "hotels#browse_by_hotel_type_in_location", :as => "browse_by_hotel_type_in_location"     
  match "browse_by/:location_name" => "hotels#browse_by_location", :as => "browse_by_location"     
  
  match "hotels/:hotel_name/details" => "hotels#show" , :as => "details"  
  match "user-profile" => "accounts#profile", :as => :user_profile
  match "/about" => "home#about"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  

#  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location" 

  match "/deals/:location_name/:type_name" => "hotels#find_by_hotel_type_in_location", :as => "find_by_hotel_type_in_location"     
  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location"   
    match "/deals" => "hotels#deals", :as =>"deals"
  root :to => "home#index"
  
end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  def index
    @room_types = RoomType.all
  end

  def show
    @room_type = RoomType.find(params[:id])
  end

  def new
    @room_type = RoomType.new
  end

  def create
    @room_type = RoomType.new(params[:room_type])
    if @room_type.save
      redirect_to @room_type, :notice => "Successfully created room type."
    else
      render :action => 'new'
    end
  end

  def edit

    @room_type = RoomType.find(params[:id])
  end

  def update
    @room_type = RoomType.find(params[:id])
    if @room_type.update_attributes(params[:room_type])
      redirect_to @room_type, :notice  => "Successfully updated room type."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @room_type = RoomType.find(params[:id])
    @room_type.destroy
    redirect_to room_types_url, :notice => "Successfully destroyed room type."
  end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.erb
<%= form_for @room_type do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/room_types/edit.html.erb
<% title "Edit Room Type" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @room_type %> |
  <%= link_to "View All", room_types_path %>
</p>

app/views/room_types/index.html.erb
<% title "Room Types" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% for room_type in @room_types %>
    <tr>
      <td><%= room_type.name %></td>
      <td><%= room_type.description %></td>
      <td><%= link_to "Show", room_type %></td>
      <td><%= link_to "Edit", edit_room_type_path(room_type) %></td>
      <td><%= link_to "Destroy", room_type, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Room Type", new_room_type_path %></p>

app/views/room_types/new.html.erb
<% title "Add Room Type Information" %>

<div class="left-area">
	<div class="win-box">
      <div class="admin">
        <h2>Menu</h2>
          	<ul>
				<li><%= link_to "Back", @hotel %></li>
			</ul>  			
      </div>			
	</div>

<%= render 'form' %>

<p><%= link_to "Back to List", room_types_path %></p>

app/views/room_types/show.html.erb
<% title "Room Type" %>

<p>
  <strong>Name:</strong>
  <%= @room_type.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @room_type.description %>
</p>

<p>
  <%= link_to "Edit", edit_room_type_path(@room_type) %> |
  <%= link_to "Destroy", @room_type, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", room_types_path %>
</p>