config/routes.rb
Hotels::Application.routes.draw do

  resources :locations

  resources :hotels_roomtypes

  get "accounts/profile"

  resources :hotel_types
  resources :room_types    
  resources :user_types
  resources :hotels_facilities
  resources :messages

  resources :hotels do
    resources :reviews
    resources :hotels_roomtypes
    resources :photos    
  end
#  resources :room_types
  resources :facilities
  devise_for :users, :path_names => {:sign_up => "register"}
  

  get "home/index"
  match "hotels/search/:location_name" => "hotels#browse_by_location", :as =>  "search_by_location"
  match "hotels/search" => "hotels#search", :as =>  "search_by"
  
  match "/contact-us" => "messages#new", :as=> "contact_us"
  match "/travel-guides" => "home#guides", :as=> "guides"
  match "/thankyou" => "messages#thankyou"
  match "/admin" =>"sessions#new"

  match "browse/:type_name/:location_name" => "hotels#find_by_location_of_hotel_type", :as => "find_by_location_of_hotel_type"  
  match "browse/:type_name" => "hotels#browse", :as => "browse_by"
  match "browse_by/:location_name/:type_name" => "hotels#browse_by_hotel_type_in_location", :as => "browse_by_hotel_type_in_location"     
  match "browse_by/:location_name" => "hotels#browse_by_location", :as => "browse_by_location"     
  
  match "hotels/:hotel_name/details" => "hotels#show" , :as => "details"  
  match "user-profile" => "accounts#profile", :as => :user_profile
  match "/about" => "home#about"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  

#  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location" 

  match "/deals/:location_name/:type_name" => "hotels#find_by_hotel_type_in_location", :as => "find_by_hotel_type_in_location"     
  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location"   
    match "/deals" => "hotels#deals", :as =>"deals"
  root :to => "home#index"
  
end

app/models/hotel.rb
include Geokit::Geocoders

class Hotel < ActiveRecord::Base
  attr_accessible :name, :address, :postcode, :phone, :fax, :location_id ,:star, :no_of_rooms, :overview, :terms, :direction,  :hotel_type_id, :photo_ids, :photo_attributes
  has_many :photos
  
  # Room Types (many-to-many)
  has_many :hotels_roomtypes,  :dependent => :destroy
  has_many :room_types, :through => :hotels_roomtypes
  
  #Hotel Type
  belongs_to :hotel_type
  belongs_to :location
  
  # Reviews
  has_many :reviews
  
	belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
	belongs_to :user
  
  # Hotel Facilities (many-to-many)
  has_many :hotels_facilities, :dependent => :destroy
  has_many :facilities, :through => :hotels_facilities
  
	validates_presence_of :name, :address, :postcode, :phone, :star, :no_of_rooms, :overview

  # Google Map
  acts_as_mappable   :default_units => :miles, 
                     :default_formula => :sphere, 
                     :distance_field_name => :distance,
                     :lat_column_name => :latitude,
                     :lng_column_name => :longitude,
                     :auto_geocode=>{:field=>:postcode, :error_message=>'Could not geocode address'}
  
    before_save :generate_longitude_latitude

	  #Get longitude and latitude from a PostCode
	  def generate_longitude_latitude
	    #Geocode the postcode
	    geocode = MultiGeocoder.geocode(self.postcode)
	    self.latitude = geocode.ll.split(",")[0]
	    self.longitude = geocode.ll.split(",")[1]
	  end

   #Get full address from longitude and latitude
   def area_address
     address=GoogleGeocoder.reverse_geocode([self.latitude,self.longitude])
     address.full_address
   end

   def self.search_with_location(google_loc, distance)

      #just set a default for distance now. might not need this once we sort the view.
      distance ||= 15 
      # ****** Removing the radius limit of the search ********
      sites = Hotel.find(:all, :origin => google_loc, :order => 'distance asc', :limit => 20 )
      #sites = Site.find(:all, :origin => google_loc, :within => distance, :order => 'distance asc', :limit => SITE_SEARCH_LIMIT, :include => :accessibilities, :conditions => ["accessibilities.code = ?", "PP"])
      #sites.delete_if {|s| !s.is_public?} #not great because it will delete sites and not give us back the right limit
   end

#  def self.hotel_owner?
#    return false if current_user.nil? || current_user.id != @hotel.owner_id
#		true		
#  end
  
#  def hotel_owner?(user)
#    return false if Self.owner_id != user.id
#    return true
#  end

  def all_hotel_locations

  end
  def self.top_hotels
    find(:all, :order => "star desc", :limit => 6)
    
  end

	def self.search(search,page)
	  loc = Location.find_by_name(search)
	  unless loc.nil?
		paginate :per_page =>5, :page => page,
								:conditions => ['address like ? OR location_id LIKE ?',"%#{search}%","%#{loc.id}%"],
								:order => 'created_at DESC'
		end						
#	search_condition = "%" + search + "%"
 #   find(:all, :conditions => ['address LIKE ? OR area LIKE ?', search_condition, search_condition])
  
	end

	def photo_attributes=(photo_attributes)
		photo_attributes.each do |attributes|
			photos.build(attributes)
		end
	end
	
	##########
  #creates the info for google popup thing
  ##########
  def map_info_window
    return "<div style=\"font-size: 14px;color:#000000;width:200px; \" ><div class='gmap_info_header'><a href='/rooms/#{self.id}'>#{self.name}</a></div></div>
  <div style=\"font-size: 10px;color:#000000;width:200px;\"><div class='gmap_info_address'><strong>Location:</strong> #{self.area}</div>
  <div class='gmap_info_address'><strong>Star:</strong>#{self.star}</div></div>"
  end
  

end

app/models/hotel_type.rb
class HotelType < ActiveRecord::Base
  has_many :hotels
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :authenticate_user!, :except => [:search, :browse, :show, :deals, :browse_by_location, :find_by_location, :find_by_hotel_type_in_location,:find_by_location_of_hotel_type, :browse_by_hotel_type_in_location]
  def index
    @menu_state_d = "class='active'"
    @top_hotels=Hotel.find(:all, :limit => 4, :order => 'star desc' )
    @hotels = Hotel.all
    @hotel_types = HotelType.all

    if params[:search].blank?
        render "search_list"
  	else
  		@hotels = Hotel.search(params[:search].downcase,params[:page])
      render "search_list"
  	end
  end
  
  def deals
    
    @menu_state_d = "class='active'"
    @top_hotels=Hotel.find(:all, :limit => 4, :order => 'star desc' )
    @hotels = Hotel.all
    @hotel_types = HotelType.all
    
    if params[:location_name]
      @loc
      render "browse_list_deals"
    else
      
      render "browse_list_deals"
    end
  end

  def show
    unless params[:hotel_name].nil?
      @hotel = Hotel.find_by_name(params[:hotel_name])
    end
    if params[:id]
      @hotel = Hotel.find(params[:id])  
    end
    @hotel_facilities = @hotel.facilities
    @hotel_reviews = @hotel.reviews
    @hotel_roomtypes = @hotel.hotels_roomtypes
    @room_type_name= @hotel.room_types.name
     	
  end

  def new
#    @hotel = Hotel.new
    @hotel = current_user.hotels.new
#    @photos = @hotel.photos.new
    @all_facilities = Facility.all
  end

  def create
    #can use? 
    @hotel =current_user.hotels.build(params[:hotel])
    @photos = @hotel.photos.new(params[:hotel])

    @all_facilities = Facility.all
  	checked_h_facilities = get_hotel_facilities_from(params[:hotel_facility_list])
  	removed_h_facilities = @all_facilities - checked_h_facilities
  	
    
    if @hotel.save
      
	    checked_h_facilities.each {|h_facility|@hotel.facilities<< h_facility if !@hotel.facilities.include?(h_facility)}
	    removed_h_facilities.each {|h_facility|@hotel.facilities.delete(h_facility) if @hotel.facilities.include?(h_facility)}

      redirect_to user_profile_path, :notice => "Successfully created hotel."
    else
      render :action => 'new'
    end
  end

  def edit
    unless params[:hotel_name].nil?
      @hotel = Hotel.find_by_name(params[:hotel_name])
    end    
    if params[:id]
      @hotel = current_user.hotels.find(params[:id])
    end
    @all_facilities = Facility.all
  end

  def update

		params[:photo_ids] ||= []
    @hotel = Hotel.find(params[:id])
		unless params[:photo_ids].empty?
			Photo.destroy_pics(params[:id], params[:photo_ids])
		end
    
    @all_facilities = Facility.all
  	checked_h_facilities = get_hotel_facilities_from(params[:hotel_facility_list])
  	removed_h_facilities = @all_facilities - checked_h_facilities
    
    if @hotel.update_attributes(params[:hotel])
      checked_h_facilities.each {|h_facility|@hotel.facilities<< h_facility if !@hotel.facilities.include?(h_facility)}
	    removed_h_facilities.each {|h_facility|@hotel.facilities.delete(h_facility) if @hotel.facilities.include?(h_facility)}
	    
      redirect_to @hotel, :notice  => "Successfully updated hotel."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @hotel = current_user.hotels.find(params[:id])
    @hotel.destroy
    redirect_to user_profile_path, :notice => "Successfully destroyed hotel."
  end
  
  def search

    @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)
    if params[:search].blank?        
        #redirect_to root_url
        @hotels = Hotel.all

  	    @hotel_types = HotelType.all
        render "search_list"
  	else
  		  @hotels = Hotel.search(params[:search].downcase,params[:page])
  	    @hotel_types = HotelType.all
      render "search_list"

  	end
  end
  
  def browse
    @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)
  	hotel_type = HotelType.find_by_name(params[:type_name])

    @hotels = Hotel.find_all_by_hotel_type_id(hotel_type.id)
    render "browse_list"
  end


  def browse_by_location
  	    @hotel_types = HotelType.all  		
        @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)
        location = Location.find_by_name(params[:location_name])
      @hotels = Hotel.find_all_by_location_id(location)

      render "browse_list"      
  end

  def browse_by_hotel_type_in_location
    @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)    
    location = Location.find_by_name(params[:location_name]) if params[:location_name]
  	hotel_type = HotelType.find_by_name(params[:type_name]) if params[:type_name]
  	@hotels = Hotel.find_all_by_location_id_and_hotel_type_id(location.id, hotel_type.id)
  	render "browse_list"
    
  end
  
  def browse_by_location_of_hotel_type


  	render "browse_list"
  end

  def find_by_location
  	    @hotel_types = HotelType.all  		
        @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)
        location = Location.find_by_name(params[:location_name])
      @hotels = Hotel.find_all_by_location_id(location)

      render "browse_list_deals"      
  end

  def find_by_hotel_type_in_location
      @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)    
      location = Location.find_by_name(params[:location_name]) if params[:location_name]
    	hotel_type = HotelType.find_by_name(params[:type_name]) if params[:type_name]
  	@hotels = Hotel.find_all_by_location_id_and_hotel_type_id(location.id, hotel_type.id)
    	render "browse_list_deals"
  end

  def find_by_location_of_hotel_type
    @top_hotels=Hotel.find(:all, :order => 'star desc', :limit => 5)    
    location = Location.find_by_name(params[:location_name])
  	hotel_type = HotelType.find_by_name(params[:type_name])
  	@hotels = Hotel.find_all_by_location_id_and_hotel_type_id(location.id, hotel_type.id)
  	render "browse_list"
    
  end
  private
	def get_hotel_facilities_from(facility_list)
		facility_list = [] if facility_list.blank?
		return facility_list.collect{|fid| Facility.find_by_id(fid.to_i)}.compact
	end
  
  
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_left_side.erb
		<div class="left-area">
			<div class="win-box">
				<div class="contact-addr">
					<div class="admin">
						<h2>
							Manage
						</h2>
						<ul>
							<li>
								<%= link_to "Manage Facilities", facilities_path %>
							</li>
							<li>
								<%= link_to "New Hotel", new_hotel_path %>
							</li>
							<li>
								<%= link_to "Edit", edit_hotel_path(hotel) %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

app/views/hotels/browse_list.html.erb
		<% content_for :head do %>
				<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAM41OPHNEzeRe7qzntS2dZxRhUbQCvgHcewKkuhV-KkriOp2HwhReuvtd5emO1MhE-giChvNKkDVHIA&amp;sensor=false" type="text/javascript"></script>
		<% end %>

		<div class="listing">
			<div class="left-area">
				<% if params[:location_name]%>
					<% if params[:type_name]%>

					<% else%>
					<div class="win-box-top"></div>
					<div class="win-box">
						<div class="info">
							<div class="heading">
								<h2 class="top-location" title="Filter by Hotel Types">
									Filter by Hotel Types
								</h2>
							</div>
							<ul>
								<% @hotel_types.each do |hotel_type|%>
									<li>
										<%= link_to hotel_type.name , browse_by_hotel_type_in_location_path(params[:location_name], hotel_type.name) %>
									</li>
								<% end %>
							</ul>
						</div>
					</div>
					<div class="win-box-bottom"></div>
					<% end %>
				<% else %>
					<% unless @hotels.blank? %>
					<div class="win-box-top"></div>
					<div class="win-box">
						<div class="info">
							<div class="heading">
								<h2 class="top-location" title="Top Locations">
									Filter by Locations
								</h2>
							</div>
							<ul>
								<% @hotels.each do |h| %>
								<li>
									<%=link_to h.location.name, find_by_location_of_hotel_type_path(params[:type_name],h.location.name) %>
								</li><% end %>
							</ul>
						</div>
					</div>
					<div class="win-box-bottom"></div>
					<% end %>					
				<% end %>
				<div class="top-rated">
					<div class="heading">
						<h2>
							Top Rated Hotels
						</h2>
					</div>
					<div class="list">
						<% @top_hotels.each do |hotel| %>
						<div class="hotel-box">
							<div class="thumb">
								<% unless hotel.photos.first.nil? %><%= image_tag hotel.photos.first.uploaded_file.url(:thumb), :alt => "" %><% end %>
							</div>
							<div class="details">
								<h3>
									<%= link_to hotel.name , details_path(hotel.name) %>
								</h3>
								<div class="loc">
									<%= hotel.location.name %>
								</div>
								<div class="s&lt;%= hotel.star %&gt;"></div>
								<div class="reviews">
									<%= link_to "Reviews (#{hotel.reviews.count})", hotel_reviews_path(hotel) %>
								</div>
							</div>
						</div><% end %>
					</div>
				</div>
			</div>
			<div class="list">
				<div class="heading">
					<h2>
						<% unless params[:search].blank? %>Hotels in <%= params[:search]%><% else %> All Hotels <% end %>
					</h2><% unless @hotels.blank? %><!--      <div class="on-the-map"><a href="#">on the map</a></div> -->
					<% end %>
				</div><% unless @hotels.blank? %><% @hotels.each do |hotel| %>
				<div class="list-block">
					<div class="box">
						<div class="thumb">
							<% unless hotel.photos.first.nil? %><%= image_tag hotel.photos.first.uploaded_file.url(:thumb), :alt => "" %><% end %>
						</div>
						<div class="details">
							<h3 class="s&lt;%= hotel.star%&gt;">
								<%= link_to hotel.name , details_path(hotel.name) %>
							</h3>
							<div class="loc">
								Location: <%= hotel.location.name %>
							</div>
							<div class="view">
								<%= link_to "View Details", hotel %>
							</div>
							<div class="price">
								From £ <span>76</span>
							</div>
						</div>
						<div class="desc">
							<p>
								<%= hotel.overview %> It is simply that wehave very high standards. There are fine restaurants with wonderful food and friendly service. People who work for us genuinely enjoy being there; everyone strives to make your stay a happy one.
							</p>
						</div><% if hotel_owner?(current_user, hotel) %>
						<div class="actions">
							<%= link_to "Edit", edit_hotel_path(hotel) %><%= link_to "Destroy", hotel, :confirm => 'Are you sure?', :method => :delete %>
						</div><% end %>
					</div>
				</div><% end  %>
				<script type="text/javascript">
				$(function(){
				if (GBrowserIsCompatible()) {
				var map = new GMap2(document.getElementById("map_canvas"));
				var points =[
				<% @hotels.each do |hotel| %>
				{
					latitude: <%=hotel.latitude%>,
					longitude: <%=hotel.longitude%>
				},

				<% end %>      
				];

				for (var i=0; i< points.length; i++) {

				map.setCenter(new GLatLng(points[i].latitude,points[i].longitude), 11);
				point =new GLatLng(points[i].latitude,points[i].longitude);
				map.addOverlay(new GMarker(point));                  
				map.setUIToDefault();

				}
				}
				});
				</script>
				<div class="map-view" style="display:block;float:left;">
					<div id="map_canvas" style="width: 560px; height: 450px"></div>
				</div><% else %>
				<p style="color:red;">
					<strong>There are currently no hotels in the list.</strong>
				</p><% end %>
			</div>
		</div>

app/views/hotels/edit.html.erb
		<div class="left-area">
			<div class="win-box">
				<div class="admin">
					<h2>
						Menu
					</h2>
					<ul>
						<li>
							<%= link_to "back", :back %>
						</li>
					</ul>
				</div>
			</div>
			<%= render :partial => 'shared/admin_menu' %>
		</div>
		<div class="main-content">
			<h2>
				Edit Hotel
			</h2>
			<%= render 'form' %>
			
		</div>

app/views/hotels/index.html.erb
<div class="left-area">
	<div class="win-box">
      <div class="admin">
        <h2>Admin</h2>
          <ul>
    				<li><%= link_to "Add New Hotel", new_hotel_path %></li>
    			</ul>  			
      </div>			
	</div>
  <%= render :partial => 'shared/admin_menu' %>      
</div>

<div class="main-content">
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Postcode</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Star</th>
    <th>No Of Rooms</th>
    <th>Overview</th>
    <th>Terms</th>
    <th>Direction</th>
  </tr>
  <% for hotel in @hotels %>
    <tr>
      <td><%= hotel.name %></td>
      <td><%= hotel.address %></td>
      <td><%= hotel.postcode %></td>
      <td><%= hotel.phone %></td>
      <td><%= hotel.fax %></td>
      <td><%= hotel.star %></td>
      <td><%= hotel.no_of_rooms %></td>
      <td><%= hotel.overview %></td>
      <td><%= hotel.terms %></td>
      <td><%= hotel.direction %></td>
      <td><%= link_to "Show", hotel %></td>
      <td><%= link_to "Edit", edit_hotel_path(hotel) %></td>
      <td><%= link_to "Destroy", hotel, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/hotels/new.html.erb
		<div class="left-area">
			<div class="win-box">
				<div class="admin">
					<h2>
						Menu
					</h2>
					<ul>
						<li>
							<%= link_to "Back to Profile", user_profile_path %>
						</li>
					</ul>
				</div>
			</div><%= render :partial => 'shared/admin_menu' %>
		</div>
		<div class="main-content">
			<%= render 'form' %>
		</div>

app/views/hotels/show.html.erb
<% javascript 'gmap','jquery.ad-gallery.js' %>
<% content_for :head do %>
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAM41OPHNEzeRe7qzntS2dZxRhUbQCvgHcewKkuhV-KkriOp2HwhReuvtd5emO1MhE-giChvNKkDVHIA&sensor=true"
          type="text/javascript"></script>
  
<% end %>
<script type="text/javascript">
$(function() {

  var galleries = $('.ad-gallery').adGallery();
  $('#switch-effect').change(
    function() {
      galleries[0].settings.effect = $(this).val();
      return false;
    }
  );
  $('#toggle-slideshow').click(
    function() {
      galleries[0].slideshow.toggle();
      return false;
    }
  );
});
</script>


<div class="breadcrumb">
    <div class="back"><% if session[:search_list] %> <%= aaa %><% else %><%= link_to "Back", :back %><% end %></div>
</div>
<div class="details">
	<div class="left">
		<div class="left-gallary">
			<div class="ad-gallery">
				<div class="ad-image-wrapper"></div>
			  	<div class="ad-nav">
			    	<div class="ad-thumbs">
			      		<ul class="ad-thumb-list">
			      		<% @hotel.photos.each do | photo | %>
			      		  	<li><%= link_to(image_tag(photo.uploaded_file.url(:thumb), :alt => ''), photo.uploaded_file.url(:original), :class => 'image1' ) %></li>				        		
                <% end unless @hotel.photos.first.new_record? rescue nil %>
			      		</ul>
			    	</div>
			  </div>		
			</div>
		</div>		
		<% if hotel_owner?(current_user ,@hotel) %>
      <%= link_to "Upload Hotel Photos", new_hotel_photo_path(@hotel) %>
    <% end %>  
		<div class="customer-reviews">
			<div class="heading">
				<h2>Customer Reviews</h2>
			</div>
			<% @hotel_reviews.each do |review|%>
      <div class="box">
        <div class="rating"><span>Guest Rating:</span> <%= review.rating %> out of 10</div>      
  			<p>
  			  <%= review.comment %>
        </p>
        <div class="by">Reviewed by Richard,  Nov 2010</div>
      </div>
      <% end %>
      <div class="action">
        <%= link_to  'Read All Reviews', hotel_reviews_path(@hotel) %>
        | 
        <%= link_to  'Write a Review', new_hotel_review_path(@hotel)%>
      </div>
		</div>	
	</div>
	<div class="right">
		<div class="hotel-details">
			<div class="hotel-addr">					
				<div class="hotel-name"><h1 class="s<%= @hotel.star %>"><%= @hotel.name %></h1></div>
				<div class="fb-like"><iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fko.aty&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe></div>					
				<div class="address"><%= @hotel.address %>, <%= @hotel.postcode %></div>
				<div class="phone">  <%= @hotel.phone %></div>
			</div>
			<div class="overview">
				<div class="heading">
					<h2 title="Overview">Overview</h2>
				</div>
				<p>  <%= @hotel.overview %></p>
				<p>Travel from business to pleasure in just a few paces, and let us demonstrate 2 wonderful extremes of hotel life.
					The first consists of our fantastic conference and meeting facilities. 
					With 11 rooms of varying size to choose from, Wifi in all rooms and fully trained staff with the 
					knowledge and expertise to run your event without a hitch.</p>
			</div>

		<div class="hotel-facilities">
			<div class="heading">
				<h2 title="Facilities">Facilities</h2>
			</div>	
			<% @hotel_facilities.each do |hotel_facility|%>
			  <ul>
			    <li><%= hotel_facility.name %></li>
			  </ul>
		  <% end %>
			</div>
			<div class="room-types">
					<h2 title="Room Types">Room Types</h2>
				<div class="table">
					<ul class="header">
						<li class="room-type"><span>Room Types</span></li>
						<li class="avail"><span>Availablity</span></li>
						<li class="price"><span>Price</span></li>
					</ul>
					<% @hotel_roomtypes.each do |room_type|%>				    
    					<ul class="row">
    						<li class="room-type"><span><%= @hotel.room_types.find_by_id(room_type.room_type_id).name %></span></li>
    						<li class="avail"><span>available</span></li>
    						<li class="price"><span>&pound;<%= room_type.price %></span></li>
    						<li class="book"><span>Call 0207 999 999 or <a href="book-online" title="Book online">Book online</a></span></li>								
      						<% if hotel_owner?(current_user, @hotel) %>
								<li class="action">
									<span><%=link_to "Edit", edit_hotel_hotels_roomtype_path(@hotel.id, room_type) %></span>
									
									<%#= link_to 'Destroy', hotel_hotels_roomtype_path(@hotel.id), :confirm => 'Are you sure?', :method => :delete %>									
								
								</li>

							<% end %>
    					</ul>
      			<% end %>
      			
      			<% if hotel_owner?(current_user, @hotel) %>
      			<ul>
  					  <li><span><%= link_to "Add Room Types", new_hotel_hotels_roomtype_path(@hotel.id), :class=>"add-room-type" %> </span></li>
  					</ul>
  					<% end %>  					
				</div>					
			</div>
			<div class="direction">
				<div class="heading">						
					<h2 title="Direction">Direction</h2>
				</div>
				  <p><%= @hotel.direction %></p>
					<p>	Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
						tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis 
						nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
					</p>
          <script type="text/javascript">
          $(function(){
            if (GBrowserIsCompatible()) {
                  var map = new google.maps.Map(document.getElementById("map_canvas"));
                  map.setCenter(new google.maps.LatLng(<%=@hotel.latitude %>, <%= @hotel.longitude %>), 15);
                  point =new GLatLng(<%=@hotel.latitude %>, <%= @hotel.longitude %>);
                  map.addOverlay(new GMarker(point));                  
                  map.setUIToDefault();
                }
          });
          </script>
		    <div id="map_canvas" style="width: 565px; height: 150px"></div>	

			</div>	
			<div class="terms">
				<div class="heading">
					<h2 title="Terms &amp; Conditions">Terms &amp; Conditions</h2>
				</div>
					<p><%= @hotel.terms %></p>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
					tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis 
					nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
					</p>
				</div>
			</div>	
			</div>					
		</div>