config/routes.rb
Hotels::Application.routes.draw do

  resources :locations

  resources :hotels_roomtypes

  get "accounts/profile"

  resources :hotel_types
  resources :room_types    
  resources :user_types
  resources :hotels_facilities
  resources :messages

  resources :hotels do
    resources :reviews
    resources :hotels_roomtypes
    resources :photos    
  end
#  resources :room_types
  resources :facilities
  devise_for :users, :path_names => {:sign_up => "register"}
  

  get "home/index"
  match "hotels/search/:location_name" => "hotels#browse_by_location", :as =>  "search_by_location"
  match "hotels/search" => "hotels#search", :as =>  "search_by"
  
  match "/contact-us" => "messages#new", :as=> "contact_us"
  match "/travel-guides" => "home#guides", :as=> "guides"
  match "/thankyou" => "messages#thankyou"
  match "/admin" =>"sessions#new"

  match "browse/:type_name/:location_name" => "hotels#find_by_location_of_hotel_type", :as => "find_by_location_of_hotel_type"  
  match "browse/:type_name" => "hotels#browse", :as => "browse_by"
  match "browse_by/:location_name/:type_name" => "hotels#browse_by_hotel_type_in_location", :as => "browse_by_hotel_type_in_location"     
  match "browse_by/:location_name" => "hotels#browse_by_location", :as => "browse_by_location"     
  
  match "hotels/:hotel_name/details" => "hotels#show" , :as => "details"  
  match "user-profile" => "accounts#profile", :as => :user_profile
  match "/about" => "home#about"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  

#  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location" 

  match "/deals/:location_name/:type_name" => "hotels#find_by_hotel_type_in_location", :as => "find_by_hotel_type_in_location"     
  match "/deals/:location_name" => "hotels#find_by_location", :as => "find_by_location"   
    match "/deals" => "hotels#deals", :as =>"deals"
  root :to => "home#index"
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def profile
   @user = User.find(current_user.id)
     @hotels = current_user.hotels
#     @hotel_room_types = current_user.hotel.room_types
#     @bookmarks = current_user.bookmarks
#     @reviews = current_user.reviews   
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_left_side.html.erb
		<div class="left-area">
			<div class="win-box-top"></div>
			<div class="win-box">
				<div class="admin">
					<h2>
						Manage
					</h2><% if admin_or_owner?(current_user.id) %>
					<ul>
						<li>
							<%= link_to "Hotels", hotels_path %>
						</li>
						<li>
							<%= link_to "Room Types", facilities_path %>
						</li>
					</ul><% end %><% if customer_user? %>
					<ul>
						<li>
							<%= link_to "Add Hotels", new_hotel_path %>
						</li><%#= link_to "Bookmarks", hotels_path %><%#= link_to "Reviews", facilities_path %>
					</ul><% end %>
				</div>
			</div>
			<div class="win-box-bottom"></div>
		</div>

app/views/accounts/profile.html.erb
<%= render :partial => 'accounts/left_side' %>      

<div class="main-content">
  <div class="heading">
    <h2>User Profile</h2>
  </div>
  <div class="acc-details">
  Username: <%= @user.username %><br />
  Email: <%= @user.email %></br />
  </div>
  <div class="my-hotels">
  <div class="heading">
    <h2>My Hotels</h2>
  </div>
<% @hotels.each do |hotel| %>

  <div class="list-block">
  	<div class="box">
  		<div id="hotel_<%= hotel.id %>" class="hotel">
  			<div class="thumb">
    			<% unless hotel.photos.first.nil? %>
    				<%= link_to image_tag(hotel.photos.first.uploaded_file.url(:thumb), :alt => ""), details_path(hotel.name)  %>
    			<% end %>
  			</div>
  			<div class="details">
  				<h3><%= link_to hotel.name , details_path(hotel.name) %></h3>
  				<div class="s<%= hotel.star %>"></div>
  				<div class="loc"><%= hotel.address %>, <%= hotel.postcode %></div>
  				<div class="price">From &pound; <span>76</span></div>
  			</div>
  			<div class="desc">
  				<p><%= hotel.overview %>
  				It is simply that wehave very high standards. There are fine restaurants with wonderful food and friendly service.  People who work for us genuinely enjoy being there;  everyone strives to make your stay a happy one.</p>
  			</div>
    		<div class="actions">
    		<%= link_to "Edit", edit_hotel_path(hotel) %><%= link_to "Destroy", hotel, :confirm => 'Are you sure?', :method => :delete %>
    		</div>

  		</div>
  	</div>
</div>  	
<% end %>
    </div>
</div>